name: Quality Checks and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run type checking
        run: npx tsc --noEmit
        
      # TODO: Add unit tests when available
      # - name: Run tests
      #   run: npm test
        
      - name: Check build compatibility (no actual build)
        run: |
          echo "✅ Linting passed"
          echo "✅ Type checking passed" 
          echo "🚀 Ready for Vercel deployment"
          
      - name: Trigger Vercel Deployment
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_QcBxUXA8tMK0SDqkQSJ5pWY1awWL/2IS2EAhxQB" 